In [37]:
# Import libraries

# First, let’s import all of the modules, functions and objects we are going to use in this tutorial.

# Load libraries
import pandas# libraries to read in the .CSV file
import numpy
from pandas.plotting import scatter_matrix
import matplotlib.pyplot as plt
from sklearn import model_selection # sci-kit learning http://scikit-learn.org/stable/
from sklearn.metrics import classification_report # measurement
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC


# Load Dataset

readdata = pandas.read_csv('meningitis_dataset.csv')
dataset = pandas.DataFrame(readdata, columns=["gender_male","gender_female","state","rural_settlement","urban_settlement",
                                              "report_year","age","age_str","disease","cholera","diarrhoea","measles",
                                              "viral_haemmorrhaphic_fever","meningitis","ebolamarburg_virus","yellow_fever",
                                              "rubella_mars","malaria","serotype","NmA","NmC","NmW","alive","dead",
                                              "report_outcome","unconfirmed","confirmed","null_serotype"])
#dataset = pandas.DataFrame(readdata, columns=["gender_male","rural_settlement","state","report_year","age","age_str","child_group","disease","serotype","alive","report_outcome","null_serotype","state"])
#dataset = pandas.DataFrame(readdata, columns=["gender_male","rural_settlement","state","report_year","age","age_str","disease","report_outcome","confirmed"])

# dataset belongs to an array type
# Summarize the Dataset

# shape
print(dataset.head(20)) #output the dimension of the data, 500 instances, 7 columns"

    gender_male  gender_female        state  rural_settlement  \
0             0              1       Rivers                 1
1             1              0       Ebonyi                 1
2             0              1         Ogun                 0
3             0              1         Ondo                 1
4             1              0          Oyo                 0
5             0              1       Kaduna                 1
6             0              1       Taraba                 1
7             1              0      Katsina                 1
8             1              0      Katsina                 1
9             0              1         Osun                 0
10            0              1        Niger                 0
11            1              0  Cross River                 1
12            1              0      Adamawa                 0
13            1              0     Nasarawa                 1
14            0              1       Ebonyi                 0
15            0              1          Imo                 0
16            1              0       Ebonyi                 0
17            1              0         Abia                 0
18            0              1        Niger                 0
19            0              1      Adamawa                 1

    urban_settlement  report_year  age   age_str        disease  cholera  ...  \
0                  0         2018   32  32 years        Cholera        1  ...
1                  0         2017   32  32 years  Marburg Virus        0  ...
2                  1         2012   24  24 years  Marburg Virus        0  ...
3                  0         2010   63  63 years        Measles        0  ...
4                  1         2017    9   9 years   Rubella Mars        0  ...
5                  0         2012   44  44 years          Ebola        0  ...
6                  0         2010   61  61 years   Yellow Fever        0  ...
7                  0         2015    2  2 months      Diarrhoea        0  ...
8                  0         2011   54  54 years   Rubella Mars        0  ...
9                  1         2014   15  15 years  Marburg Virus        0  ...
10                 1         2015   17  17 years        Cholera        1  ...
11                 0         2012   50  50 years      Diarrhoea        0  ...
12                 1         2012    4   4 years        Measles        0  ...
13                 0         2016    3   3 years          Ebola        0  ...
14                 1         2011   59  59 years     Meningitis        0  ...
15                 1         2012    2  2 months     Meningitis        0  ...
16                 1         2015   49  49 years     Meningitis        0  ...
17                 1         2011   48  48 years     Meningitis        0  ...
18                 1         2010   30  30 years        Cholera        1  ...
19                 0         2017   39  39 years        Malaria        0  ...

                                serotype  NmA  NmC  NmW  alive  dead  \
0                          null serotype    0    0    0      1     0
1                                   Null    0    0    1      1     0
2                                   Null    0    0    1      0     1
3                                   Null    0    0    1      1     0
4                                   Null    0    0    1      1     0
5                                   Null    0    0    1      1     0
6                                   Null    0    0    1      1     0
7                                   Null    0    0    1      1     0
8                                   Null    0    0    1      1     0
9                                   Null    0    0    1      1     0
10                                  Null    0    0    1      1     0
11                                  Null    0    0    1      1     0
12                                  Null    0    0    1      0     1
13                                  Null    0    0    1      1     0
14  Neisseria meningitidis group A (NmA)    1    0    0      0     1
15  Neisseria meningitidis group W (NmW)    0    0    1      1     0
16  Neisseria meningitidis group W (NmW)    0    0    1      0     1
17  Neisseria meningitidis group A (NmA)    1    0    0      0     1
18                                  Null    0    0    1      0     1
19                                  Null    0    0    1      1     0

    report_outcome  unconfirmed confirmed  null_serotype
0        confirmed            0         1              1
1        Confirmed            1         0              1
2    Not Confirmed            1         0              1
3    Not Confirmed            1         0              1
4        Confirmed            1         0              1
5        Confirmed            1         0              1
6        Confirmed            0         1              1
7    Not Confirmed            1         0              1
8        Confirmed            1         0              1
9        Confirmed            1         0              1
10   Not Confirmed            1         0              1
11   Not Confirmed            1         0              1
12       Confirmed            0         1              1
13   Not Confirmed            1         0              1
14   Not Confirmed            1         0              0
15   Not Confirmed            1         0              0
16   Not Confirmed            1         0              0
17   Not Confirmed            1         0              0
18       Confirmed            0         1              1
19   Not Confirmed            1         0              1

[20 rows x 28 columns]

In [ ]:
import pandas
readdata = pandas.read_csv('meningitis_dataset.csv')
dataset4 = pandas.DataFrame(readdata, columns=["id","surname","firstname","middlename","gender_male","gender_female","state","settlement","rural_settlement","urban_settlement","report_date","report_year","age","age_str","date_of_birth","child_group","a","disease","cholera","diarrhoea","measles","viral_haemmorrhaphic_fever","meningitis","ebolamarburg_virus","yellow_fever","rubella_mars","malaria","serotype","NmA","NmC","NmW","alive","dead","report_outcome","unconfirmed","confirmed","null_serotype"])
cat={"cholera","diarrhoea","measles","viral_haemmorrhaphic_fever","meningitis","ebolamarburg_virus","yellow_fever","rubella_mars","malaria","NmA","NmC","NmW"}#,"alive","dead","unconfirmed","confirmed","null_serotype"}

TtestPvalue=[]
from scipy.stats import ttest_ind

cat1 = dataset4[dataset4["confirmed"]==1]
cat2 = dataset4[dataset4["confirmed"]==0]

for CatName in cat:
    #ttest_ind(cat1[CatName], cat2[CatName])
    TtestPvalue.append(CatName+": Pvalue="+str(ttest_ind(cat1[CatName], cat2[CatName]).pvalue))

print(TtestPvalue)
#ttest_ind(cat1["age"], cat2["age"]) #pvalue=0.038085358962017965
#ttest_ind(cat1["state"], cat2["state"])# pvalue=0.8291323533811423
#ttest_ind(cat1["rural_settlement"], cat2["rural_settlement"]) #pvalue=0.32930652294193763
#ttest_ind(cat1["report_year"], cat2["report_year"]) #pvalue=0.41446156826221414

In [ ]:

# 检测dataset数据类型
dataset.dtypes

In [ ]:
# 查看数据例子
print(dataset.head(20))

In [38]:
# 丢去任何除了yellow fever的疾病
dataset2 = dataset#[(dataset.disease == 'Yellow Fever')]# & (dataset.report_outcome == 'Confirmed')]
dataset2.reset_index(inplace=True)
dataset2 = dataset2.drop('index',1)
#print(dataset2.describe())
dataset2.to_csv(r'output.csv')
print(dataset2.head(200))

     gender_male  gender_female        state  rural_settlement  \
0              0              1       Rivers                 1
1              1              0       Ebonyi                 1
2              0              1         Ogun                 0
3              0              1         Ondo                 1
4              1              0          Oyo                 0
5              0              1       Kaduna                 1
6              0              1       Taraba                 1
7              1              0      Katsina                 1
8              1              0      Katsina                 1
9              0              1         Osun                 0
10             0              1        Niger                 0
11             1              0  Cross River                 1
12             1              0      Adamawa                 0
13             1              0     Nasarawa                 1
14             0              1       Ebonyi                 0
15             0              1          Imo                 0
16             1              0       Ebonyi                 0
17             1              0         Abia                 0
18             0              1        Niger                 0
19             0              1      Adamawa                 1
20             0              1         Yobe                 1
21             0              1       Rivers                 0
22             0              1        Delta                 1
23             1              0         Ogun                 1
24             0              1       Jigawa                 1
25             1              0        Borno                 1
26             0              1      Adamawa                 0
27             0              1        Kwara                 0
28             1              0  Cross River                 0
29             0              1         Yobe                 0
..           ...            ...          ...               ...
170            0              1         Yobe                 1
171            0              1       Jigawa                 1
172            1              0        Gombe                 1
173            1              0          Edo                 1
174            1              0        Kwara                 0
175            0              1         Yobe                 1
176            0              1      Plateau                 0
177            1              0        Ekiti                 1
178            0              1       Sokoto                 0
179            0              1        Enugu                 1
180            1              0        Kwara                 1
181            1              0          Oyo                 0
182            0              1        Ekiti                 1
183            0              1        Borno                 0
184            1              0       Rivers                 0
185            0              1          Imo                 0
186            0              1         Ondo                 1
187            1              0       Taraba                 0
188            0              1      Zamfara                 0
189            1              0        Gombe                 1
190            1              0         Abia                 1
191            1              0       Taraba                 1
192            1              0         Osun                 1
193            0              1         Ondo                 1
194            0              1         Yobe                 0
195            0              1       Rivers                 0
196            0              1         Kogi                 1
197            0              1          Edo                 1
198            0              1         Ondo                 0
199            1              0       Bauchi                 0

     urban_settlement  report_year  age    age_str  \
0                   0         2018   32   32 years
1                   0         2017   32   32 years
2                   1         2012   24   24 years
3                   0         2010   63   63 years
4                   1         2017    9    9 years
5                   0         2012   44   44 years
6                   0         2010   61   61 years
7                   0         2015    2   2 months
8                   0         2011   54   54 years
9                   1         2014   15   15 years
10                  1         2015   17   17 years
11                  0         2012   50   50 years
12                  1         2012    4    4 years
13                  0         2016    3    3 years
14                  1         2011   59   59 years
15                  1         2012    2   2 months
16                  1         2015   49   49 years
17                  1         2011   48   48 years
18                  1         2010   30   30 years
19                  0         2017   39   39 years
20                  0         2010   50   50 years
21                  1         2011   14   14 years
22                  0         2016   41   41 years
23                  0         2009   59   59 years
24                  0         2018   45   45 years
25                  0         2018    5    5 years
26                  1         2018   72   72 years
27                  1         2016    7    7 years
28                  1         2015   16   16 years
29                  1         2014    7   7 months
..                ...          ...  ...        ...
170                 0         2011   69   69 years
171                 0         2009   10   10 years
172                 0         2014   65   65 years
173                 0         2017   13   13 years
174                 1         2015   44   44 years
175                 0         2015   61   61 years
176                 1         2018   62   62 years
177                 0         2013   23   23 years
178                 1         2009    5   5 months
179                 0         2009   10  10 months
180                 0         2015   72   72 years
181                 1         2011   68   68 years
182                 0         2011   20   20 years
183                 1         2017   48   48 years
184                 1         2017   65   65 years
185                 1         2016   32   32 years
186                 0         2010    8   8 months
187                 1         2009   60   60 years
188                 1         2011   11   11 years
189                 0         2018   71   71 years
190                 0         2013   37   37 years
191                 0         2009   34   34 years
192                 0         2010   65   65 years
193                 0         2011    9    9 years
194                 1         2010   42   42 years
195                 1         2011   48   48 years
196                 0         2018   69   69 years
197                 0         2012   69   69 years
198                 1         2014   26   26 years
199                 1         2015   72   72 years

                        disease  cholera  ...  \
0                       Cholera        1  ...
1                 Marburg Virus        0  ...
2                 Marburg Virus        0  ...
3                       Measles        0  ...
4                  Rubella Mars        0  ...
5                         Ebola        0  ...
6                  Yellow Fever        0  ...
7                     Diarrhoea        0  ...
8                  Rubella Mars        0  ...
9                 Marburg Virus        0  ...
10                      Cholera        1  ...
11                    Diarrhoea        0  ...
12                      Measles        0  ...
13                        Ebola        0  ...
14                   Meningitis        0  ...
15                   Meningitis        0  ...
16                   Meningitis        0  ...
17                   Meningitis        0  ...
18                      Cholera        1  ...
19                      Malaria        0  ...
20                 Rubella Mars        0  ...
21                      Malaria        0  ...
22                      Measles        0  ...
23                    Diarrhoea        0  ...
24                Marburg Virus        0  ...
25   Viral Haemmorrhaphic Fever        0  ...
26                 Yellow Fever        0  ...
27   Viral Haemmorrhaphic Fever        0  ...
28                Marburg Virus        0  ...
29                Marburg Virus        0  ...
..                          ...      ...  ...
170                     Malaria        0  ...
171                     Measles        0  ...
172                Yellow Fever        0  ...
173                     Malaria        0  ...
174               Marburg Virus        0  ...
175                   Diarrhoea        0  ...
176                     Measles        0  ...
177                Yellow Fever        0  ...
178                     Malaria        0  ...
179                Yellow Fever        0  ...
180                     Measles        0  ...
181                     Malaria        0  ...
182                     Malaria        0  ...
183                       Ebola        0  ...
184                     Malaria        0  ...
185               Marburg Virus        0  ...
186                Rubella Mars        0  ...
187                Yellow Fever        0  ...
188  Viral Haemmorrhaphic Fever        0  ...
189                     Malaria        0  ...
190                     Cholera        1  ...
191                     Cholera        1  ...
192                     Malaria        0  ...
193                  Meningitis        0  ...
194                     Cholera        1  ...
195  Viral Haemmorrhaphic Fever        0  ...
196                   Diarrhoea        0  ...
197                     Malaria        0  ...
198               Marburg Virus        0  ...
199                     Measles        0  ...

                                 serotype  NmA  NmC  NmW  alive  dead  \
0                           null serotype    0    0    0      1     0
1                                    Null    0    0    1      1     0
2                                    Null    0    0    1      0     1
3                                    Null    0    0    1      1     0
4                                    Null    0    0    1      1     0
5                                    Null    0    0    1      1     0
6                                    Null    0    0    1      1     0
7                                    Null    0    0    1      1     0
8                                    Null    0    0    1      1     0
9                                    Null    0    0    1      1     0
10                                   Null    0    0    1      1     0
11                                   Null    0    0    1      1     0
12                                   Null    0    0    1      0     1
13                                   Null    0    0    1      1     0
14   Neisseria meningitidis group A (NmA)    1    0    0      0     1
15   Neisseria meningitidis group W (NmW)    0    0    1      1     0
16   Neisseria meningitidis group W (NmW)    0    0    1      0     1
17   Neisseria meningitidis group A (NmA)    1    0    0      0     1
18                                   Null    0    0    1      0     1
19                                   Null    0    0    1      1     0
20                                   Null    0    0    1      0     1
21                                   Null    0    0    1      1     0
22                                   Null    0    0    1      1     0
23                                   Null    0    0    1      0     1
24                                   Null    0    0    1      0     1
25                                   Null    0    0    1      1     0
26                                   Null    0    0    1      1     0
27                                   Null    0    0    1      0     1
28                                   Null    0    0    1      1     0
29                                   Null    0    0    1      1     0
..                                    ...  ...  ...  ...    ...   ...
170                                  Null    0    0    1      0     1
171                                  Null    0    0    1      1     0
172                                  Null    0    0    1      1     0
173                                  Null    0    0    1      1     0
174                                  Null    0    0    1      1     0
175                                  Null    0    0    1      0     1
176                                  Null    0    0    1      1     0
177                                  Null    0    0    1      0     1
178                                  Null    0    0    1      1     0
179                                  Null    0    0    1      0     1
180                                  Null    0    0    1      0     1
181                                  Null    0    0    1      0     1
182                                  Null    0    0    1      1     0
183                                  Null    0    0    1      1     0
184                                  Null    0    0    1      1     0
185                                  Null    0    0    1      1     0
186                                  Null    0    0    1      0     1
187                                  Null    0    0    1      0     1
188                                  Null    0    0    1      0     1
189                                  Null    0    0    1      0     1
190                                  Null    0    0    1      0     1
191                                  Null    0    0    1      1     0
192                                  Null    0    0    1      1     0
193  Neisseria meningitidis group W (NmW)    0    0    1      1     0
194                                  Null    0    0    1      0     1
195                                  Null    0    0    1      0     1
196                                  Null    0    0    1      1     0
197                                  Null    0    0    1      0     1
198                                  Null    0    0    1      0     1
199                                  Null    0    0    1      0     1

     report_outcome  unconfirmed confirmed  null_serotype
0         confirmed            0         1              1
1         Confirmed            1         0              1
2     Not Confirmed            1         0              1
3     Not Confirmed            1         0              1
4         Confirmed            1         0              1
5         Confirmed            1         0              1
6         Confirmed            0         1              1
7     Not Confirmed            1         0              1
8         Confirmed            1         0              1
9         Confirmed            1         0              1
10    Not Confirmed            1         0              1
11    Not Confirmed            1         0              1
12        Confirmed            0         1              1
13    Not Confirmed            1         0              1
14    Not Confirmed            1         0              0
15    Not Confirmed            1         0              0
16    Not Confirmed            1         0              0
17    Not Confirmed            1         0              0
18        Confirmed            0         1              1
19    Not Confirmed            1         0              1
20        Confirmed            1         0              1
21        Confirmed            0         1              1
22        Confirmed            0         1              1
23        Confirmed            0         1              1
24        Confirmed            1         0              1
25    Not Confirmed            1         0              1
26        Confirmed            0         1              1
27        Confirmed            1         0              1
28    Not Confirmed            1         0              1
29        Confirmed            1         0              1
..              ...          ...       ...            ...
170   Not Confirmed            1         0              1
171   Not Confirmed            1         0              1
172   Not Confirmed            1         0              1
173   Not Confirmed            1         0              1
174   Not Confirmed            1         0              1
175       Confirmed            0         1              1
176   Not Confirmed            1         0              1
177       Confirmed            0         1              1
178       Confirmed            0         1              1
179       Confirmed            0         1              1
180   Not Confirmed            1         0              1
181       Confirmed            0         1              1
182   Not Confirmed            1         0              1
183       Confirmed            1         0              1
184   Not Confirmed            1         0              1
185   Not Confirmed            1         0              1
186       Confirmed            1         0              1
187       Confirmed            0         1              1
188   Not Confirmed            1         0              1
189       Confirmed            0         1              1
190   Not Confirmed            1         0              1
191       Confirmed            0         1              1
192       Confirmed            0         1              1
193       Confirmed            1         0              0
194       Confirmed            0         1              1
195       Confirmed            1         0              1
196   Not Confirmed            1         0              1
197   Not Confirmed            1         0              1
198       Confirmed            1         0              1
199   Not Confirmed            1         0              1

[200 rows x 28 columns]

In [39]:
# 将所有以月为单位的年龄改为年份单位
count = len(dataset2.index)
for i in range(0,count): #遍历每一个row
    # age string
    if dataset2.iloc[i,7][-5:] == "onths": # 如果age string结尾是onths 
        dataset2.iloc[i,6] = (dataset2.iloc[i,4])/12 #将此单元格对应的月份除12得到相对应的年份

print(dataset2.head(20))

    gender_male  gender_female        state  rural_settlement  \
0             0              1       Rivers                 1
1             1              0       Ebonyi                 1
2             0              1         Ogun                 0
3             0              1         Ondo                 1
4             1              0          Oyo                 0
5             0              1       Kaduna                 1
6             0              1       Taraba                 1
7             1              0      Katsina                 1
8             1              0      Katsina                 1
9             0              1         Osun                 0
10            0              1        Niger                 0
11            1              0  Cross River                 1
12            1              0      Adamawa                 0
13            1              0     Nasarawa                 1
14            0              1       Ebonyi                 0
15            0              1          Imo                 0
16            1              0       Ebonyi                 0
17            1              0         Abia                 0
18            0              1        Niger                 0
19            0              1      Adamawa                 1

    urban_settlement  report_year        age   age_str        disease  \
0                  0         2018  32.000000  32 years        Cholera
1                  0         2017  32.000000  32 years  Marburg Virus
2                  1         2012  24.000000  24 years  Marburg Virus
3                  0         2010  63.000000  63 years        Measles
4                  1         2017   9.000000   9 years   Rubella Mars
5                  0         2012  44.000000  44 years          Ebola
6                  0         2010  61.000000  61 years   Yellow Fever
7                  0         2015   0.000000  2 months      Diarrhoea
8                  0         2011  54.000000  54 years   Rubella Mars
9                  1         2014  15.000000  15 years  Marburg Virus
10                 1         2015  17.000000  17 years        Cholera
11                 0         2012  50.000000  50 years      Diarrhoea
12                 1         2012   4.000000   4 years        Measles
13                 0         2016   3.000000   3 years          Ebola
14                 1         2011  59.000000  59 years     Meningitis
15                 1         2012   0.083333  2 months     Meningitis
16                 1         2015  49.000000  49 years     Meningitis
17                 1         2011  48.000000  48 years     Meningitis
18                 1         2010  30.000000  30 years        Cholera
19                 0         2017  39.000000  39 years        Malaria

    cholera  ...                              serotype  NmA  NmC  NmW  alive  \
0         1  ...                         null serotype    0    0    0      1
1         0  ...                                  Null    0    0    1      1
2         0  ...                                  Null    0    0    1      0
3         0  ...                                  Null    0    0    1      1
4         0  ...                                  Null    0    0    1      1
5         0  ...                                  Null    0    0    1      1
6         0  ...                                  Null    0    0    1      1
7         0  ...                                  Null    0    0    1      1
8         0  ...                                  Null    0    0    1      1
9         0  ...                                  Null    0    0    1      1
10        1  ...                                  Null    0    0    1      1
11        0  ...                                  Null    0    0    1      1
12        0  ...                                  Null    0    0    1      0
13        0  ...                                  Null    0    0    1      1
14        0  ...  Neisseria meningitidis group A (NmA)    1    0    0      0
15        0  ...  Neisseria meningitidis group W (NmW)    0    0    1      1
16        0  ...  Neisseria meningitidis group W (NmW)    0    0    1      0
17        0  ...  Neisseria meningitidis group A (NmA)    1    0    0      0
18        1  ...                                  Null    0    0    1      0
19        0  ...                                  Null    0    0    1      1

    dead  report_outcome  unconfirmed confirmed  null_serotype
0      0       confirmed            0         1              1
1      0       Confirmed            1         0              1
2      1   Not Confirmed            1         0              1
3      0   Not Confirmed            1         0              1
4      0       Confirmed            1         0              1
5      0       Confirmed            1         0              1
6      0       Confirmed            0         1              1
7      0   Not Confirmed            1         0              1
8      0       Confirmed            1         0              1
9      0       Confirmed            1         0              1
10     0   Not Confirmed            1         0              1
11     0   Not Confirmed            1         0              1
12     1       Confirmed            0         1              1
13     0   Not Confirmed            1         0              1
14     1   Not Confirmed            1         0              0
15     0   Not Confirmed            1         0              0
16     1   Not Confirmed            1         0              0
17     1   Not Confirmed            1         0              0
18     1       Confirmed            0         1              1
19     0   Not Confirmed            1         0              1

[20 rows x 28 columns]

In [36]:
print(dataset2.tail(20))

        gender_male  gender_female                      state  \
284464            1              0                       Ogun
284465            0              1                     Ebonyi
284466            0              1                       Ondo
284467            0              1                       Ondo
284468            0              1  Federal Capital Territory
284469            1              0                     Kaduna
284470            1              0                       Kogi
284471            0              1                       Kogi
284472            0              1                       Osun
284473            0              1                       Kogi
284474            1              0                        Oyo
284475            1              0                      Borno
284476            0              1                     Taraba
284477            0              1                       Ondo
284478            1              0                       Yobe
284479            0              1                Cross River
284480            0              1                      Kwara
284481            0              1                    Katsina
284482            1              0                     Jigawa
284483            0              1                       Kogi

        rural_settlement  urban_settlement  report_year        age   age_str  \
284464                 0                 1         2011  68.000000  68 years
284465                 0                 1         2012   0.083333  2 months
284466                 1                 0         2017  60.000000  60 years
284467                 1                 0         2016  10.000000  10 years
284468                 0                 1         2017  11.000000  11 years
284469                 1                 0         2012  29.000000  29 years
284470                 1                 0         2009  34.000000  34 years
284471                 0                 1         2010   0.083333  4 months
284472                 0                 1         2009  43.000000  43 years
284473                 0                 1         2015  10.000000  10 years
284474                 0                 1         2009   0.083333  1 months
284475                 0                 1         2011  45.000000  45 years
284476                 1                 0         2009  69.000000  69 years
284477                 0                 1         2015  42.000000  42 years
284478                 0                 1         2010  22.000000   22 days
284479                 1                 0         2012  67.000000  67 years
284480                 0                 1         2009  64.000000  64 years
284481                 1                 0         2010  33.000000  33 years
284482                 1                 0         2016  18.000000  18 years
284483                 0                 1         2013   0.083333  7 months

                           disease  cholera  ...  \
284464  Viral Haemmorrhaphic Fever        0  ...
284465                Rubella Mars        0  ...
284466                Yellow Fever        0  ...
284467  Viral Haemmorrhaphic Fever        0  ...
284468                  Meningitis        0  ...
284469                  Meningitis        0  ...
284470                Rubella Mars        0  ...
284471                  Meningitis        0  ...
284472                Yellow Fever        0  ...
284473                     Measles        0  ...
284474                  Meningitis        0  ...
284475                     Cholera        1  ...
284476                   Diarrhoea        0  ...
284477  Viral Haemmorrhaphic Fever        0  ...
284478               Marburg Virus        0  ...
284479                       Ebola        0  ...
284480                       Ebola        0  ...
284481                     Malaria        0  ...
284482                     Malaria        0  ...
284483                Yellow Fever        0  ...

                                    serotype  NmA  NmC  NmW  alive  dead  \
284464                                  Null    0    0    1      1     0
284465                                  Null    0    0    1      0     1
284466                                  Null    0    0    1      1     0
284467                                  Null    0    0    1      1     0
284468  Neisseria meningitidis group W (NmW)    0    0    1      0     1
284469  Neisseria meningitidis group C (NmC)    0    1    0      1     0
284470                                  Null    0    0    1      1     0
284471  Neisseria meningitidis group W (NmW)    0    0    1      1     0
284472                                  Null    0    0    1      0     1
284473                                  Null    0    0    1      1     0
284474  Neisseria meningitidis group W (NmW)    0    0    1      0     1
284475                                  Null    0    0    1      1     0
284476                                  Null    0    0    1      0     1
284477                                  Null    0    0    1      0     1
284478                                  Null    0    0    1      1     0
284479                                  Null    0    0    1      0     1
284480                                  Null    0    0    1      0     1
284481                                  Null    0    0    1      1     0
284482                                  Null    0    0    1      0     1
284483                                  Null    0    0    1      1     0

        report_outcome  unconfirmed confirmed  null_serotype
284464       Confirmed            1         0              1
284465       Confirmed            1         0              1
284466       Confirmed            0         1              1
284467   Not Confirmed            1         0              1
284468   Not Confirmed            1         0              0
284469       Confirmed            1         0              0
284470   Not Confirmed            1         0              1
284471       Confirmed            1         0              0
284472   Not Confirmed            1         0              1
284473       Confirmed            0         1              1
284474   Not Confirmed            1         0              0
284475       Confirmed            0         1              1
284476   Not Confirmed            1         0              1
284477   Not Confirmed            1         0              1
284478       Confirmed            1         0              1
284479       Confirmed            1         0              1
284480       Confirmed            1         0              1
284481       Confirmed            0         1              1
284482   Not Confirmed            1         0              1
284483       Confirmed            0         1              1

[20 rows x 28 columns]

In [42]:
# 将所有的confirmed改为1，Not Confirmed改为0
count = len(dataset2.index)
for i in range(3,count): #遍历每一个row
    # age string
    if dataset2.iloc[i,24][:3] == "Not": # report outcome是Not开始 
        dataset2.iloc[i,24] = 0 #将此单元格变成
    else:
        dataset2.iloc[i,24] = 1 #其他的就是confirmed了，变成1

print(dataset2.head(20))

    gender_male  gender_female        state  rural_settlement  \
0             0              1       Rivers                 1
1             1              0       Ebonyi                 1
2             0              1         Ogun                 0
3             0              1         Ondo                 1
4             1              0          Oyo                 0
5             0              1       Kaduna                 1
6             0              1       Taraba                 1
7             1              0      Katsina                 1
8             1              0      Katsina                 1
9             0              1         Osun                 0
10            0              1        Niger                 0
11            1              0  Cross River                 1
12            1              0      Adamawa                 0
13            1              0     Nasarawa                 1
14            0              1       Ebonyi                 0
15            0              1          Imo                 0
16            1              0       Ebonyi                 0
17            1              0         Abia                 0
18            0              1        Niger                 0
19            0              1      Adamawa                 1

    urban_settlement  report_year        age   age_str        disease  \
0                  0         2018  32.000000  32 years        Cholera
1                  0         2017  32.000000  32 years  Marburg Virus
2                  1         2012  24.000000  24 years  Marburg Virus
3                  0         2010  63.000000  63 years        Measles
4                  1         2017   9.000000   9 years   Rubella Mars
5                  0         2012  44.000000  44 years          Ebola
6                  0         2010  61.000000  61 years   Yellow Fever
7                  0         2015   0.000000  2 months      Diarrhoea
8                  0         2011  54.000000  54 years   Rubella Mars
9                  1         2014  15.000000  15 years  Marburg Virus
10                 1         2015  17.000000  17 years        Cholera
11                 0         2012  50.000000  50 years      Diarrhoea
12                 1         2012   4.000000   4 years        Measles
13                 0         2016   3.000000   3 years          Ebola
14                 1         2011  59.000000  59 years     Meningitis
15                 1         2012   0.083333  2 months     Meningitis
16                 1         2015  49.000000  49 years     Meningitis
17                 1         2011  48.000000  48 years     Meningitis
18                 1         2010  30.000000  30 years        Cholera
19                 0         2017  39.000000  39 years        Malaria

    cholera  ...                              serotype  NmA  NmC  NmW  alive  \
0         1  ...                         null serotype    0    0    0      1
1         0  ...                                  Null    0    0    1      1
2         0  ...                                  Null    0    0    1      0
3         0  ...                                  Null    0    0    1      1
4         0  ...                                  Null    0    0    1      1
5         0  ...                                  Null    0    0    1      1
6         0  ...                                  Null    0    0    1      1
7         0  ...                                  Null    0    0    1      1
8         0  ...                                  Null    0    0    1      1
9         0  ...                                  Null    0    0    1      1
10        1  ...                                  Null    0    0    1      1
11        0  ...                                  Null    0    0    1      1
12        0  ...                                  Null    0    0    1      0
13        0  ...                                  Null    0    0    1      1
14        0  ...  Neisseria meningitidis group A (NmA)    1    0    0      0
15        0  ...  Neisseria meningitidis group W (NmW)    0    0    1      1
16        0  ...  Neisseria meningitidis group W (NmW)    0    0    1      0
17        0  ...  Neisseria meningitidis group A (NmA)    1    0    0      0
18        1  ...                                  Null    0    0    1      0
19        0  ...                                  Null    0    0    1      1

    dead  report_outcome  unconfirmed confirmed  null_serotype
0      0               1            0         1              1
1      0               1            1         0              1
2      1               0            1         0              1
3      0               0            1         0              1
4      0               1            1         0              1
5      0               1            1         0              1
6      0               1            0         1              1
7      0               0            1         0              1
8      0               1            1         0              1
9      0               1            1         0              1
10     0               0            1         0              1
11     0               0            1         0              1
12     1               1            0         1              1
13     0               0            1         0              1
14     1               0            1         0              0
15     0               0            1         0              0
16     1               0            1         0              0
17     1               0            1         0              0
18     1               1            0         1              1
19     0               0            1         0              1

[20 rows x 28 columns]

In [43]:
#state的list
state = ['Abi','Ada','Akw','Ana','Bau','Bay','Ben','Bor','Cro','Del','Ebo','Edo','Eki','Enu','Fed','Gom','Imo','Jig','Kad','Kan','Kat','Keb','Kog','Kwa','Lag','Nas','Nig','Ogu','Ond','Osu','Oyo','Pla','Riv','Sok','Tar','Yob','Zam']
print(len(state))
print(state)

37
['Abi', 'Ada', 'Akw', 'Ana', 'Bau', 'Bay', 'Ben', 'Bor', 'Cro', 'Del', 'Ebo', 'Edo', 'Eki', 'Enu', 'Fed', 'Gom', 'Imo', 'Jig', 'Kad', 'Kan', 'Kat', 'Keb', 'Kog', 'Kwa', 'Lag', 'Nas', 'Nig', 'Ogu', 'Ond', 'Osu', 'Oyo', 'Pla', 'Riv', 'Sok', 'Tar', 'Yob', 'Zam']

In [44]:
# 改state
count = len(dataset2.index)
for i in range(0,count): #遍历每一个数据
    num = 1
    for j in state: 
        if dataset2.iloc[i,2][:3] == j: # state前三个字母和state_list一样 
            dataset2.iloc[i,2] = num#将此单元格变成num
            break #跳出
        num = num+1

print(dataset2.head(20))

    gender_male  gender_female  state  rural_settlement  urban_settlement  \
0             0              1     33                 1                 0
1             1              0     11                 1                 0
2             0              1     28                 0                 1
3             0              1     29                 1                 0
4             1              0     31                 0                 1
5             0              1     19                 1                 0
6             0              1     35                 1                 0
7             1              0     21                 1                 0
8             1              0     21                 1                 0
9             0              1     30                 0                 1
10            0              1     27                 0                 1
11            1              0      9                 1                 0
12            1              0      2                 0                 1
13            1              0     26                 1                 0
14            0              1     11                 0                 1
15            0              1     17                 0                 1
16            1              0     11                 0                 1
17            1              0      1                 0                 1
18            0              1     27                 0                 1
19            0              1      2                 1                 0

    report_year        age   age_str        disease  cholera  ...  \
0          2018  32.000000  32 years        Cholera        1  ...
1          2017  32.000000  32 years  Marburg Virus        0  ...
2          2012  24.000000  24 years  Marburg Virus        0  ...
3          2010  63.000000  63 years        Measles        0  ...
4          2017   9.000000   9 years   Rubella Mars        0  ...
5          2012  44.000000  44 years          Ebola        0  ...
6          2010  61.000000  61 years   Yellow Fever        0  ...
7          2015   0.000000  2 months      Diarrhoea        0  ...
8          2011  54.000000  54 years   Rubella Mars        0  ...
9          2014  15.000000  15 years  Marburg Virus        0  ...
10         2015  17.000000  17 years        Cholera        1  ...
11         2012  50.000000  50 years      Diarrhoea        0  ...
12         2012   4.000000   4 years        Measles        0  ...
13         2016   3.000000   3 years          Ebola        0  ...
14         2011  59.000000  59 years     Meningitis        0  ...
15         2012   0.083333  2 months     Meningitis        0  ...
16         2015  49.000000  49 years     Meningitis        0  ...
17         2011  48.000000  48 years     Meningitis        0  ...
18         2010  30.000000  30 years        Cholera        1  ...
19         2017  39.000000  39 years        Malaria        0  ...

                                serotype  NmA  NmC  NmW  alive  dead  \
0                          null serotype    0    0    0      1     0
1                                   Null    0    0    1      1     0
2                                   Null    0    0    1      0     1
3                                   Null    0    0    1      1     0
4                                   Null    0    0    1      1     0
5                                   Null    0    0    1      1     0
6                                   Null    0    0    1      1     0
7                                   Null    0    0    1      1     0
8                                   Null    0    0    1      1     0
9                                   Null    0    0    1      1     0
10                                  Null    0    0    1      1     0
11                                  Null    0    0    1      1     0
12                                  Null    0    0    1      0     1
13                                  Null    0    0    1      1     0
14  Neisseria meningitidis group A (NmA)    1    0    0      0     1
15  Neisseria meningitidis group W (NmW)    0    0    1      1     0
16  Neisseria meningitidis group W (NmW)    0    0    1      0     1
17  Neisseria meningitidis group A (NmA)    1    0    0      0     1
18                                  Null    0    0    1      0     1
19                                  Null    0    0    1      1     0

    report_outcome  unconfirmed confirmed  null_serotype
0                1            0         1              1
1                1            1         0              1
2                0            1         0              1
3                0            1         0              1
4                1            1         0              1
5                1            1         0              1
6                1            0         1              1
7                0            1         0              1
8                1            1         0              1
9                1            1         0              1
10               0            1         0              1
11               0            1         0              1
12               1            0         1              1
13               0            1         0              1
14               0            1         0              0
15               0            1         0              0
16               0            1         0              0
17               0            1         0              0
18               1            0         1              1
19               0            1         0              1

[20 rows x 28 columns]

In [45]:
dataset2.to_csv(r'output.csv')

In [ ]:
#population
population = {2009:154324933,2010:158503197,2011:162805071,2012:167228767,2013:171765769,2014:176404902,2015:181137448,2016:185960289,2017:190873311,2018:195874740}
print(population[2009])

#GNI
GNI = {2009:2040,2010:2140,2011:2190,2012:2460,2013:2720,2014:2990,2015:2880,2016:2470,2017:2100,2018:1960}
print(GNI[2009])

#GDP
GDP = {2009:291880204327.419, 2010:363359886203.409, 2011:410334579160.752, 2012:459376049763.999, 2013:514966287334.277, 2014:568498937615.656, 2015:494583180777.103, 2016:404649527537.753, 2017:375745486520.656, 2018:397269616080.908}
print(GDP[2009])

In [ ]:
#删除多余column
dataset3 = dataset2
dataset3 = dataset3.drop("age_str",1)
dataset3 = dataset3.drop('disease',1)
print(dataset3.head(40))

In [ ]:
zero = numpy.zeros(28428)
dataset3['population'] = zero
dataset3['gdp'] = zero
dataset3['gni'] = zero
#dataset3['temperature'] = zero
#dataset3['rainfall'] = zero
print(dataset3.head(20))

In [ ]:
# 改population,gdp, gni
count = len(dataset3.index)
for i in range(0,count): #遍历每一个数据
    dataset3.iloc[i,7] = population[dataset3.iloc[i,3]] #改变人口
    dataset3.iloc[i,8] = GDP[dataset3.iloc[i,3]] #改变GDP
    dataset3.iloc[i,9] = GNI[dataset3.iloc[i,3]] #改变GNI

print(dataset3.head(20))

In [ ]:
# dataset3 = dataset3.drop('temperature',1)
# dataset3 = dataset3.drop('rainfall',1)
print(dataset3.head(20))
dataset3.hist(figsize=(200,160))
plt.show()

In [ ]:
import matplotlib.pyplot as plt

plt.matshow(dataset3.corr())
colorbar = plt.colorbar()
plt.show()

In [ ]:
from scipy.stats import ttest_ind

cat1 = dataset3[dataset3["confirmed"]==1]
cat2 = dataset3[dataset3["confirmed"]==0]

ttest_ind(cat1["age"], cat2["age"]) #pvalue=0.038085358962017965
#ttest_ind(cat1["state"], cat2["state"])# pvalue=0.8291323533811423
#ttest_ind(cat1["rural_settlement"], cat2["rural_settlement"]) #pvalue=0.32930652294193763
#ttest_ind(cat1["report_year"], cat2["report_year"]) #pvalue=0.41446156826221414

In [ ]:
a = ['gender_male', 'rural_settlement', 'state', 'report_year', 'age', 'confirmed']#'population', 'gdp', 'gni',

In [ ]:
dataset_train = dataset3[dataset3.report_year != 2018] #挑出2018年的数据
dataset_train.reset_index(inplace=True) #重设index
dataset_train = dataset_train.drop('index',1)
dataset_train = dataset_train[a]
print(dataset_train.head(20))

plt.matshow(dataset_train.corr())
colorbar = plt.colorbar()
plt.show()

#print(dataset_train.shape)
from sklearn import preprocessing
interm_x_train = dataset_train.values
scaler = preprocessing.MinMaxScaler()
scaled_x_train = scaler.fit_transform(interm_x_train)
dataset_train= pandas.DataFrame(scaled_x_train)
print(dataset_train.head(20))

array = dataset_train.values
X_train = array[:,[0,1,2,4]]
y_train = array[:,5]
print(X_train)

In [ ]:
dataset_test = dataset3[dataset3.report_year ==  2017] #挑出2018年的数据
dataset_test.reset_index(inplace=True) #重设index
dataset_test = dataset_test.drop('index',1)

dataset_test = dataset_test[a]
#print(dataset_test.head(20))
#print(dataset_test.shape)

interm_x_test = dataset_test.values
scaled_x_test = scaler.fit_transform(interm_x_test)
dataset_test= pandas.DataFrame(scaled_x_test)
print(dataset_test.head(20))

array = dataset_test.values
X_test = array[:,[0,1,2,4]] 
y_test = array[:,5]
print(X_test)

In [ ]:
#from sklearn import decomposition
#pca = decomposition.PCA(n_components=8)
#pca.fit(X_train)
#pca.fit(X_test)
#X_train = pca.transform(X_train)
#X_test = pca.transform(X_test)

print(X_test)
print(X_train)

In [ ]:
#Random Forest 

from sklearn.tree import DecisionTreeClassifier        #Decision Tree
from sklearn.ensemble import RandomForestClassifier    #Random Forest
from sklearn.neural_network import MLPClassifier

training_accuracy = []
test_accuracy = []

max_dep = range(1,34)
neighbors_setting = range(1,34) # can be modified
min_samples_splits = numpy.linspace(0.1, 1.0, 10, endpoint=True)

for md in max_dep:
#for min_samples_split in min_samples_splits:
        tree = DecisionTreeClassifier(max_depth=md,random_state=0,max_features=0.9)
        tree.fit(X_train,y_train)
        training_accuracy.append(tree.score(X_train, y_train))
        test_accuracy.append(tree.score(X_test, y_test))
 

plt.plot(max_dep,training_accuracy, label='Accuracy of the training set')
plt.plot(neighbors_setting,test_accuracy, label='Accuracy of the test set')
#plt.plot(min_samples_splits,training_accuracy, label='Accuracy of the training set')
#plt.plot(min_samples_splits,test_accuracy, label='Accuracy of the test set')
plt.ylabel('Accuracy')
plt.xlabel('Max Depth')
plt.legend()

# by looking at plot, best result occurs when max_depth is > 4

In [ ]:
#KNN
training_accuracy = []
test_accuracy = []

#try KNN for diffrent k nearest neighbor from 1 to 15
neighbors_setting = range(1,20) # can be modified

for n_neighbors in neighbors_setting:
    knn = KNeighborsClassifier(n_neighbors=n_neighbors)
    knn.fit(X_train,y_train)
    training_accuracy.append(knn.score(X_train, y_train))
    test_accuracy.append(knn.score(X_test, y_test))
 
plt.plot(neighbors_setting,training_accuracy, label='Accuracy of the training set')
plt.plot(neighbors_setting,test_accuracy, label='Accuracy of the test set')
plt.ylabel('Accuracy')
plt.xlabel('Number of Neighbors')
plt.legend()
#by looking at plot, best result accurs when n_neighbors is 1-4

In [ ]:
#logistic Regression #Remark: Logistic regression doesn't generate good results
log_reg = LogisticRegression()
log_reg.fit(X_train, y_train)

print('Accuracy on the training set: {:.3f}'.format(log_reg.score(X_train,y_train)))
print('Accuracy on the test set: {:.3f}'.format(log_reg.score(X_test,y_test)))

#It seems as it does better than KNN

In [ ]:
from sklearn.ensemble import RandomForestClassifier 
forest = RandomForestClassifier(n_estimators=100, random_state=0)
forest.fit(X_train,y_train)

#you can tune parameter such as:
# - n_job (how many cores)(n_job=-1 => all cores)
# - max_depth
# - max_feature


print('acc for training data: {:.3f}'.format(forest.score(X_train,y_train)))
print('acc for test data: {:.3f}'.format(forest.score(X_test,y_test)))

In [ ]:
from sklearn.neural_network import MLPClassifier
#mlp = MLPClassifier(hidden_layer_sizes=(6,6,6,6,6,6,),max_iter=1000)
mlp = MLPClassifier(solver='sgd', activation='relu',alpha=1e-4,hidden_layer_sizes=(50,50,50), 
                    random_state=20,max_iter=100,verbose=10,learning_rate_init=.01, learning_rate='adaptive')
mlp.fit(X_train, y_train)

print('acc for training data: {:.3f}'.format(mlp.score(X_train, y_train)))
print('acc for test data: {:.3f}'.format(mlp.score(X_test, y_test)))

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit(X_train).transform(X_train)
X_test_scaled = scaler.fit(X_test).transform(X_test)

mlp = MLPClassifier(max_iter=1000, random_state=42)
mlp.fit(X_train_scaled, y_train)

print('acc for training data: {:.3f}'.format(mlp.score(X_train_scaled, y_train)))
print('acc for test data: {:.3f}'.format(mlp.score(X_test_scaled, y_test)))
print("Training set loss: %f" % mlp.loss_)

In [ ]:
from sklearn.svm import SVC 
svm= SVC()
svm.fit(X_train, y_train)

print('acc on train dataset: {:.3f}'.format(svm.score(X_train,y_train)))
print('acc on test dataset: {:.3f}'.format(svm.score(X_test,y_test)))

In [ ]:
svm = SVC()
svm.fit(X_train_scaled, y_train)
print('acc on train dataset: {:.3f}'.format(svm.score(X_train_scaled,y_train)))
print('acc on test dataset: {:.3f}'.format(svm.score(X_test_scaled,y_test)))

In [ ]:
svm = SVC(C=1000)
svm.fit(X_train_scaled, y_train)
print('acc on train dataset: {:.3f}'.format(svm.score(X_train_scaled,y_train)))
print('acc on test dataset: {:.3f}'.format(svm.score(X_test_scaled,y_test)))